### ISSUE TITLE
setTimeoutResponse method not found

### ISSUE THREAD

**Issue by hswick** [marvin-we/steem-java-api-wrapper#128]
Following in the instructions [here](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/sample/src/main/java/my/sample/project/SteemJUsageExample.java) and was receiving an error setTimeoutResponse. Used clojure.reflect and noticed that this isn't a method, but setTimeout is

**Comment by hswick** [comment]
Same issue with setDefaultAccount, I'm just going to assume the documentation is out of date.

**Comment by marvin-we** [comment]
Hello again @hswick and thank you for reporting this issue :) 

Actually the `setTimeoutResponse` is available as you can see here 

https://github.com/marvin-we/steem-java-api-wrapper/blob/57b52e5af8a4243c1c9e6b1bf4497148e84d0da6/core/src/main/java/eu/bittrade/libs/steemj/configuration/SteemJConfig.java#L430

Same for the 'setDefaultAccount':

https://github.com/marvin-we/steem-java-api-wrapper/blob/57b52e5af8a4243c1c9e6b1bf4497148e84d0da6/core/src/main/java/eu/bittrade/libs/steemj/configuration/SteemJConfig.java#L479

So something seems to be strange here - Could you please describe to me how you added SteemJ to your project and which version you use? Maybe I did a mistake during the deployment :(

Thank you very much and best regards!

**Comment by hswick** [comment]
Well setSocketTimeout isn't setTimeoutResponse lol ;)
I am following this documentation https://github.com/marvin-we/steem-java-api-wrapper/blob/master/sample/src/main/java/my/sample/project/SteemJUsageExample.java
Added steemj via leiningen, the classes are available, but the methods specified in this example do not seem to be working.

**Comment by marvin-we** [comment]
Hello @hswick and sorry for the late reply :( I had a quite busy week.

In general: The sample of the master branch which you've just linked may differ from what is available in the latest official release as the master branch always contains the latest state of the development. So right now it may contain fields which are will be introduced with SteemJ 0.4.1, but are not available right now.

To get the correct sample for the version you are using select the tag of the version you use:

![Screenshot](https://imgur.com/TcbWsH3.png)

I also rechecked what I have deployed by downloading the sources from http://central.maven.org/maven2/eu/bittrade/libs/steemj-core/0.4.0/ and the SteemJConfig class contains all methods you mention. 

Could you please make sure that you really use SteemJ 0.4.0 ? I don't know what else could be wrong :( 

Please keep me updated!

Thank you and best regards

**Comment by hswick** [comment]
I deleted the old package in my local maven repo and changed the code to follow along with your example. Everything works, good job!

**Comment by marvin-we** [comment]
Haha, thank you for keeping me updated - I was a little bit afraid that I've messed something up :D 

Glad that its now working for you <3
