### ISSUE TITLE
Improvements for simplified operations (createPost/createComment)

### ISSUE THREAD

**Issue by ray66rus** [marvin-we/steem-java-api-wrapper#133]
There are some things that, in my opinion, can improve functionality of these method while not making usage too complex:

1. To allow the user change default beneficiary. It's mostly important when you use the network where is no "steemj" account (testnet/golos/any other possible fork of steem). I think that the most simple way is to check steemJWeight value and if it's set to zero just don't include beneficiaries list into the comment options.
2. To allow the user to add arbitrary json metadata to the post. Again, I see the very simple and straightforward way to do this. You have "createPost" method with the following signatures: createPost(String, String, String[]) and createPost(String, String, String[]) and createPost(AccountName, String, String, String[]). So if you just add two more: createPost(String, String, String) and commentPost(String, String, String[]) and createPost(AccountName, String, String, String) and the user can add arbitrary metadata. The same with the "createComment".

Both of theese changes should be very easy to implement, they don't make the usage of the library any harder while giving the user a lot of flexabilty

**Comment by marvin-we** [comment]
I totally agree with point one.

From my point of view the "Support SteemJ feature" or whatever you want to call it :D Is something that should not be part of steemj-core at all. It should be part of the wallet projects that I am planning to realize for the specific chains.

I will go for the change you've suggest for now and remove it completly from SteemJ-Core when there is a first prototype of a wallet project for Steem.

Would that be fine for you too?

**Comment by ray66rus** [comment]
Yep, thanks :)

**Comment by marvin-we** [comment]
Step one has been implement - If you have more suggestions just update the ticket :) I'll leave it open.
