### ISSUE TITLE
Problem with big head block number

### ISSUE THREAD

**Issue by ray66rus** [marvin-we/steem-java-api-wrapper#137]
Get the following error:
```
[Grizzly(1)] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Raw JSON response: {"id":22,"result":{"id":0,"head_block_number":575526,"head_block_id":"0008c82654aa6a0c2f704b1966e3b7ea2bf4fe65","time":"2017-10-22T17:24:54","current_witness":"initminer","total_pow":"18446744073709551615","num_pow_witnesses":0,"virtual_supply":"11822607.000 TESTS","current_supply":"11822607.000 TESTS","confidential_supply":"0.000 TESTS","current_sbd_supply":"0.000 TBD","confidential_sbd_supply":"0.000 TBD","total_vesting_fund_steem":"10096035.000 TESTS","total_vesting_shares":"6000000.000000 VESTS","total_reward_fund_steem":"1151052.000 TESTS","total_reward_shares2":"0","pending_rewarded_vesting_shares":"0.000000 VESTS","pending_rewarded_vesting_steem":"0.000 TESTS","sbd_interest_rate":1000,"sbd_print_rate":10000,"maximum_block_size":131072,"current_aslot":19028898,"recent_slots_filled":"340282366920938463463374607431768211455","participation_count":128,"last_irreversible_block_num":575505,"vote_power_reserve_rate":40,"current_reserve_ratio":200000000,"average_block_size":121,"max_virtual_bandwidth":"528482304000000000000"}}


<=steem_post. Exception while posting: Value is out of range : 575307
org.joou.UShort.rangeCheck(UShort.java:139)
org.joou.UShort.<init>(UShort.java:107)
org.joou.UShort.valueOf(UShort.java:93)
eu.bittrade.libs.steemj.base.models.Transaction.<init>(Transaction.java:109)
eu.bittrade.libs.steemj.base.models.SignedTransaction.<init>(SignedTransaction.java:0)
eu.bittrade.libs.steemj.SteemJ.createComment(SteemJ.java:2817)
org.veg.androidcamtrans.api.SteemAPI.createComment(SteemAPI.java:347)
org.veg.androidcamtrans.api.SteemAPI.createComment(SteemAPI.java:323)
org.veg.androidcamtrans.api.SteemAPI.postOffer(SteemAPI.java:442)
org.veg.androidcamtrans.api.HTTPDoc.steem_post(HTTPDoc.java:4503)
org.veg.androidcamtrans.api.HTTPUpload$HTTPSteemPostThread.runt(HTTPUpload.java:522)
org.veg.androidcamtrans.api.ThreadHelper.run(ThreadHelper.java:46)
java.lang.Thread.run(Thread.java:818)
```

As you can see from the debug message, the head block number in my testnet is pretty big (575526) here. It fits in long datatype perfectly ("private long headBlockNumber" in GlobalProperties.java), but fail to be converted to UShort in Transaction constractor (this.setRefBlockNum(UShort.valueOf(blockId.getNumberFromHash())) in Transaction.java).

**Comment by marvin-we** [comment]
Hello again @ray66rus  :D :) 

thank you once again for reporting this issue. I've checked the original Steem Code which looks like this:

```C++
uint16_t           ref_block_num    = 0;
uint32_t           ref_block_prefix = 0;
```

So I guess using UShort and UInteger should be the correct :'( .

Could you tell me from where you got the refBlockNumber? Was it just a random number you choosed or is it returned by the testnet?

**Comment by ray66rus** [comment]
Hi again :) It's a testnet. I slightly modified your code and truncated the number to fit the ushort - changed this.setRefBlockNum(UShort.valueOf(blockId.getNumberFromHash())) to this.setRefBlockNum(UShort.valueOf(blockId.getNumberFromHash() & 0xffff)) and it works, but I don't know, if it is a legitimate :)

**Comment by marvin-we** [comment]
Hm - Seems like you've found something strange once again 🎉 

The ref block number returned by the dynamic global properties method returns a Uint32:

```C++
uint32_t database::head_block_num()const
{
   return get_dynamic_global_properties().head_block_number;
}
```

So according to google this assigning an intenger to a short variable is like casting it:

> The cast is unnecessary. Assignment, initialization, parameter passing, and return statements can assign values between any numeric types without a cast. The value is converted implicitly:
>
>short b = a;

Which means that adding `& 0xffff` should do the trick 👍 

Let me sleep about this for one night :D I guess I'll change and commit it tomorrow :)
