### ISSUE TITLE
 No static field INSTANCE error on Android 

### ISSUE THREAD

**Issue by filippkowalski** [marvin-we/steem-java-api-wrapper#146]
When I try to use library on Android I get following error : 
`java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)`
possible solution might be found here : https://stackoverflow.com/questions/27366430/getting-nosuchfielderror-instance-org-apache-http-message-basicheadervalueparser

**Comment by marvin-we** [comment]
I'll do some tests with the official Google HTTP Client as an alternative (see https://mvnrepository.com/artifact/com.google.http-client/google-http-client/1.23.0)

**Comment by marvin-we** [comment]
Switching from Apache to the Google HTTP client was easier than expected and according to the documentation (see https://developers.google.com/api-client-library/java/google-http-java-client/android ) it should work on every system.. I will release a pre-release to give you the possibility to test this.

**Comment by marvin-we** [comment]
@filippkowalski confirmed via steemit.chat that 0.4.3-pre1 is working now - Thanks for all the effort you spend on this topic and good luck for your project!
