### ISSUE TITLE
Document default benificiary in the JavaDoc too

### ISSUE THREAD

**Issue by michael-newsrx** [marvin-we/steem-java-api-wrapper#158]
Hi,
Was testing the library and created a post that I was wanting to delete.
The delete failed with no votes or comments, so went and looked in steemdb at the post and see
```
{
            "beneficiaries": [
                {
                    "account": "steemj",
                    "weight": 250
                }
            ]
        }
```

Please add the fact the library is automatically setting a 2.5% beneficiary to steemj in the readme which is on the main repo page.

Fantastic work btw.

**Comment by marvin-we** [comment]
Hay @michael-newsrx ,

Thank you for reporting this. I will check the wiki and the javadoc and add this information in case its still missing there :)

You can configure the percentage using SteemJConfig and if set to 0 it wont attach the comment_options_operation at all.

Thanks once again and best regards!

**Comment by marvin-we** [comment]
This was already documented [in the wiki](https://github.com/marvin-we/steem-java-api-wrapper/wiki/SteemJConfig#steemjWeight) . I will add it to the JavaDoc of the post and comment method.
