### ISSUE TITLE
Reblog issue

### ISSUE THREAD

**Issue by grzegorz2047** [marvin-we/steem-java-api-wrapper#212]
Hi, 
I'm using steemJ-core 0.4.3 and I want to reblog some content. When I use this version: 
```
steemJ.reblog(firstPostAuthor, permlinkToPost);

```
It runs in code fine, but output (in steemd) is:
![noresteem](https://user-images.githubusercontent.com/1348001/35770239-ea179edc-0917-11e8-8642-b4d3b5edeb0c.PNG)
And it doesn't resteem as it supposed to resteem. Any ideas why?
My default account has been set, posting keys are in place, am i missing something?
Here is a full source code with line, where I use reblog method:
https://github.com/grzegorz2047/PolishJavaSteemitBot/blob/master/src/main/java/pl/grzegorz2047/polishjavasteemitbot/CommentingBot.java#L91

**Comment by grzegorz2047** [comment]
It's because it puts "rebloag" instead of "follow"

**Comment by muksihs** [comment]
The API docs show the id should read "reblog" and not "follow":

```json
[
  "custom_json",
  {
    "required_auths": [],
    "required_posting_auths": ["bob"],
    "id": "reblog",
    "json": "{\"account\":\"bob\",\"author\":\"alice\",\"permlink\":\"a-post-by-alice\"}"
  }
]
```

https://developers.steem.io/apidefinitions/#broadcast_ops_custom_json

**Comment by muksihs** [comment]
Verified the id should be "follow" via busy.org browser post capture:
```json
{"operations":[["custom_json",{"required_auths":[],"required_posting_auths":["muksihs"],"id":"follow","json":"[\"reblog\",{\"account\":\"muksihs\",\"author\":\"steemitblog\",\"permlink\":\"update-on-unexpected-voting-power-behavior\"}]"}]]}
```
