### ISSUE TITLE
Compile Time Errors

### ISSUE THREAD

**Issue by saggammahesh** [marvin-we/steem-java-api-wrapper#22]
Hi,
I've pulled the code but i see compile time errors. Basically few classes are missing. Below are the errors.
1. The import eu.bittrade.libs.steem.api.wrapper.models.FutureExtensions cannot be resolved
2.The import eu.bittrade.libs.steem.api.wrapper.models.CommentOptionsExtension cannot be resolved

**Comment by marvin-we** [comment]
Thank you for the report saggammahesh. Seems like I haven't committed all changes - Could you try to pull the latest revision?

**Comment by saggammahesh** [comment]
yes i tried to pull again. Still i see same errors.

**Comment by marvin-we** [comment]
Should finally be solved.

**Comment by saggammahesh** [comment]
Yes solved. I able to run mvn clean install.
I would like to explore api and probably would like to contribute also.
Thanks for taking this initiative to create API

**Comment by marvin-we** [comment]
You are welcome - Thank you for reporting that issue 👍 

Sounds great. Just let me know if you face an issue or a missing a feature.
