### ISSUE TITLE
Trending Posts Not accessible

### ISSUE THREAD

**Issue by abhi3700** [marvin-we/steem-java-api-wrapper#220]
Hello, 
Can u please help me in getting the 'trending posts' from steem blockchain by tags ?
E.g.
```getTrendingPosts(tag:"bitcoin");   // shows all the trending posts under the tag 'bitcoin' ```
&
 ```getTrendingPosts();    // shows all the trending posts irrespective of a tag ```

Please, help me  folks.....

Thanks!!..
Happy Coding ...

**Comment by muksihs** [comment]
(untested, but should point you in the correct direction)
```
		SteemJ() steemJ = new SteemJ()

		DiscussionSortType sortBy=DiscussionSortType.GET_DISCUSSIONS_BY_TRENDING;
		DiscussionQuery discussionQuery=new DiscussionQuery();
		List<String> filterTags=new ArrayList<>();
		filterTags.add("far-horizons");
		discussionQuery.setFilterTags(filterTags);
		discussionQuery.setLimit(100);
		List<Discussion> discussions;
		try {
			discussions = steemJ.getDiscussionsBy(discussionQuery, sortBy);
		} catch (SteemCommunicationException | SteemResponseException e) {
			throw new RuntimeException(e);
		}
		for (Discussion discussion: discussions) {
			System.out.println("=== "+discussion.getTitle());
			System.out.println(""+discussion.getBody());
		}

```

**Comment by abhi3700** [comment]
@muksihs 
Thanks!!..for the help...
Shall try and let you know ....

Thanks again!!...
