### ISSUE TITLE
SteemJ initialization issue

### ISSUE THREAD

**Issue by bxute** [marvin-we/steem-java-api-wrapper#222]
While I am trying to create an object of SteemJ.
```
SteemJ steemJ = new SteemJ();
```
It throws error:

```
W: eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
W:     at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
W:     at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
W:     at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
W:     at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
W:     at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
W:     at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)

```

I am using gradle dependency: `eu.bittrade.libs:steemj-core:0.4.3`

As I can see, the `get_api_by_name` is abandoned. But how we can incorporate this into our project.

**Comment by grzegorz2047** [comment]
you can resolve it using this method: https://github.com/marvin-we/steem-java-api-wrapper/issues/223

**Comment by bxute** [comment]
`{"jsonrpc":"2.0","error":{
"code":-32002,"message":"Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"json_rpc_plugin.cpp","line":206,"method":"find_api_method","hostname":"","timestamp":"2018-03-26T06:50:43"},"format":"method_itr != api_itr->second.end(): Could not find method ${method}","data":{"method":"get_api_by_name"}}]}},"id":4720018877021266836}`

Can you please explain this response.

**Comment by grzegorz2047** [comment]
@bxute It means that "get_api_by_name" is no longer available in steem api. SteemJ is using "get_api_by_name" which doesn't exist. One user fixed that problem in his fork and I used his version in my project. I simply linked his compiled jar file in my pom.xml and executed install-file before compiling.

**Comment by muksihs** [comment]
Try using this fork for now:

https://jitpack.io/#muksihs/steem-java-api-wrapper/5b30f72

**Comment by muksihs** [comment]
Resolved in latest merge.
