### ISSUE TITLE
Unrecognized field "init_sbd_supply"

### ISSUE THREAD

**Issue by tiagoferezin** [marvin-we/steem-java-api-wrapper#235]
java.lang.IllegalArgumentException: Unrecognized field "init_sbd_supply" (class eu.bittrade.libs.steemj.base.models.DynamicGlobalProperty), not marked as ignorable (29 known properties: "current_reserve_ratio", "confidential_supply", "num_pow_witnesses", "total_reward_shares2", "sbd_interest_rate", "head_block_id", "time", "confidential_sbd_supply", "participation_count", "average_block_size", "pending_rewarded_vesting_steem", "current_aslot", "id", "total_vesting_shares", "total_pow", "max_virtual_bandwidth", "virtual_supply", "total_reward_fund_steem", "pending_rewarded_vesting_shares", "maximum_block_size", "current_witness", "current_supply", "head_block_number", "sbd_print_rate", "current_sbd_supply", "recent_slots_filled", "vote_power_reserve_rate", "total_vesting_fund_steem", "last_irreversible_block_num"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.lang.Object[0]->eu.bittrade.libs.steemj.base.models.DynamicGlobalProperty["init_sbd_supply"])
	com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3688)
	eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleResult(JsonRPCResponse.java:164)
	eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:124)
	eu.bittrade.libs.steemj.SteemJ.getDynamicGlobalProperties(SteemJ.java:1077)
	eu.bittrade.libs.steemj.SteemJ.vote(SteemJ.java:2423)
	com.herokuapp.javasteemapi.controller.BotController.rodar(BotController.java:135)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:781)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:721)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:176)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

**Comment by marvin-we** [comment]
Hay @tiagoferezin ,

thank you for reporting this - I guess the main reason is that this lib was not maintained anymore since steem moved forward. So the wrapper is incompatible :/ 

Lets see how long it will take to get it updated.
