### ISSUE TITLE
Implement follow_api

### ISSUE THREAD

**Issue by marvin-we** [marvin-we/steem-java-api-wrapper#25]
see [post on steemit](https://steemit.com/steem-dev/@dez1337/steemj-v0-2-6-has-been-released-update-11#@sesangsokuro/re-dez1337-steemj-v0-2-6-has-been-released-update-11-20170615t125408838z)

**Comment by sesangsokuro** [comment]
thanks!

**Comment by marvin-we** [comment]
Hay @sesangsokuro,

I've added all methods of the follow_api. I am not sure how fast I will be with the documentation, but if you do not want to wait for it you can simply have a look at the unit tests (see src\test\java\eu\bittrade\libs\steemj\SteemApiWrapperIT.java).

Best regards!
