### ISSUE TITLE
Discussion can not be resolved to type

### ISSUE THREAD

**Issue by saggammahesh** [marvin-we/steem-java-api-wrapper#27]
Latest code has compilation issues.
Please commit class Discussion.

**Comment by marvin-we** [comment]
Hay saggammahesh,

sorry for the late reply. I've now checked it twice (downloading the zip and cloning the repo) and I am able to build the project in both cases :/ The [Discussion](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/src/main/java/eu/bittrade/libs/steem/api/wrapper/models/Discussion.java) class is also committed.

If you are using "git pull" you may face some caching issues?

**Comment by marvin-we** [comment]
Hay @saggammahesh,

I'll release version 0.3.0 today. If you still face this issue please try to use the Jar attached to the release. 

Thanks for the support and best regards!
