### ISSUE TITLE
exception in jackson json mapping

### ISSUE THREAD

**Issue by alexpmorris** [marvin-we/steem-java-api-wrapper#28]
if seems there's an error in the json mapping / databind which pops up when trying to look at a relatively newer account.  If I replace it with my account ( @alexpmorris or yours @dez1337 ), it works fine.  For example, if I try this one:

> Map<Integer, AccountActivity> accountHistory = steemApiWrapper.getAccountHistory("randowhale", 100, 100);

It results in the following exception:

> Exception in thread "main" java.lang.IllegalArgumentException: Conflicting getter definitions for property "memo_key": eu.bittrade.libs.steem.api.wrapper.models.operations.AccountCreateWithDelegationOperation#getMemoKey(0 params) vs eu.bittrade.libs.steem.api.wrapper.models.operations.AccountCreateWithDelegationOperation#getJson_metadata(0 params)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: eu.bittrade.libs.steem.api.wrapper.models.AccountActivity["op"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3726)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3654)
	at eu.bittrade.libs.steem.api.wrapper.SteemApiWrapper.getAccountHistory(SteemApiWrapper.java:211)
	at SteemAPIUsageExample.main(SteemAPIUsageExample.java:47)

**Comment by marvin-we** [comment]
Hay alexpmorris,

thanks for the report :) I've just added the following assertion to the integration test:

```JAVA
final Map<Integer, AccountActivity> accountHistorySetTwo = steemApiWrapper.getAccountHistory(ACCOUNT_TWO, 1000,
                1000);
        assertEquals("expect response to contain 101 results", 1001, accountHistorySetTwo.size());

        assertThat(accountHistorySetTwo.get(0).getOperations(), instanceOf(AccountCreateWithDelegationOperation.class));
        assertThat(((AccountCreateWithDelegationOperation) accountHistorySetTwo.get(0).getOperations()).getCreator()
                .getAccountName(), equalTo(new AccountName("anonsteem").getAccountName()));
```
and it is working fine for me. Could you let me know which version you are using and which Steem node you are connected to? 

Thanks and best regards!

**Comment by alexpmorris** [comment]
everything I did was pretty much off the readme.  Used the version you listed there (0.2.3) loaded in pom.xml as a maven project, along with the example you gave in the readme, which uses the ``wss://this.piston.rocks`` endpoint.  And I pretty much only changed your userid to randowhale or another newer user, and commented out the private keys.  Hope that helps!

**Comment by marvin-we** [comment]
That helps a lot :) Version 0.2.3 really has this issue, but it has been fixed in the meantime. If you update to version 0.2.6 it should work.

**Comment by alexpmorris** [comment]
okay that worked, thanks!  though it looks like you've been busy with many changes since 0.2.3. Had to comment a bunch of things out from the sample app to get it to run (probably just a few other class renames), as well as change SteemApiWrapperConfig -> SteemJConfig!  Still, keep up the great work, I know it's a big undertaking! :)

**Comment by marvin-we** [comment]
Yes, I totally agree on that. There will be some more changes with 0.3.0 and I'll try to update the documention with that release :)
