### ISSUE TITLE
 Dependencies needed to use this library

### ISSUE THREAD

**Issue by sesangsokuro** [marvin-we/steem-java-api-wrapper#35]
<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.8.8</version>
			<type>bundle</type>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.8</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.8.8</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.tyrus.bundles</groupId>
			<artifactId>tyrus-standalone-client</artifactId>
			<version>1.13.1</version>
		</dependency>
		<dependency>
			<groupId>org.bitcoinj</groupId>
			<artifactId>bitcoinj-core</artifactId>
			<version>0.14.4</version>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.exparity</groupId>
			<artifactId>hamcrest-date</artifactId>
			<version>2.0.4</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>com.madgag.spongycastle</groupId>
			<artifactId>core</artifactId>
			<version>1.56.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.madgag.spongycastle</groupId>
			<artifactId>prov</artifactId>
			<version>1.56.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.madgag.spongycastle</groupId>
			<artifactId>pkix</artifactId>
			<version>1.54.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.madgag.spongycastle</groupId>
			<artifactId>pg</artifactId>
			<version>1.54.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk15on</artifactId>
			<version>1.57</version>
		</dependency>

I did not build it in Maven before I added it.

I want to add this to the wiki. Please add it as a contributor.

**Comment by marvin-we** [comment]
Hay @sesangsokuro,

this only occurs if you download / use the *.jar file directly - It does not occur if you use SteemJ as a Maven depency, right? If this is the case it can be fixed by adding the maven-assembly plugin to the StemmJ pom.xml to create a jar containing all depedencies :) 

Btw: I've added you as a Contributor to this project.

Thanks for the help and best regards!

**Comment by sesangsokuro** [comment]
I did not know there was a maven-assembly plug-in. I need to write both methods on the wiki.

Thank you for inviting me as a contributor.

But I have another question yesterday and I will add it as a new issue because it is kind of different.

I do not know if I can post a question on the issue. #36

**Comment by marvin-we** [comment]
Hay @sesangsokuro ,

I've added the maven-assembly-plugin. If you will now run "mvn clean install -Dmaven.test.skip.exec" you should be able to find a "steem-api-wrapper-0.X.X-jar-with-dependencies.jar" file. This jar contains all required depedencies.

I'll add this jar to the release page for all future releases. :) 

Best regards!
