### ISSUE TITLE
Error in JSON responses when fetching order information

### ISSUE THREAD

**Issue by FullKickProductions** [marvin-we/steem-java-api-wrapper#37]
Calling `steemApiWrapper.getOrderBook(1)` results in an error response.
`15:01:23.360 [AWT-EventQueue-0] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Raw JSON response: {"id":9,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nitr != _by_name.end(): no method with name 'get_order_book'\n    {\"name\":\"get_order_book\",\"api\":{\"get_api_by_name\":1,\"get_version\":2,\"login\":0}}\n    th_a  api_connection.hpp:109 call\n\n    {\"call.method\":\"call\",\"call.params\":[\"login_api\",\"get_order_book\",[\"1\"]]}\n    th_a  websocket_api.cpp:124 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api_connection.hpp","line":109,"method":"call","hostname":"","thread_name":"th_a","timestamp":"2017-06-28T13:01:23"},"format":"itr != _by_name.end(): no method with name '${name}'","data":{"name":"get_order_book","api":{"get_api_by_name":1,"get_version":2,"login":0}}},{"context":{"level":"warn","file":"websocket_api.cpp","line":124,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-06-28T13:01:23"},"format":"","data":{"call.method":"call","call.params":["login_api","get_order_book",["1"]]}}]}}}
15:01:23.368 [AWT-EventQueue-0] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Could not parse the response. Trying to transform it to an error object.`

Could there be something wrong with my config? I geta similar error when calling `steemApiWrapper.getFeedHistory()`

This is my first issue on github, so please forgive me if I've missed any important steps.

**Comment by sesangsokuro** [comment]
When I tested steemApiWrapper.getFeedHistory () in version 0.31, I got the same error too ( I think ).

Eu.bittrade.libs.steemj.exceptions.SteemResponseError
At eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest (CommunicationHandler.java:161)
At eu.bittrade.libs.steemj.SteemApiWrapper.getFeedHistory (SteemApiWrapper.java:731)
At steemit2.SteemAPIUsageExample.main (SteemAPIUsageExample.java:354)

That's it.

follow lines was my "Myconfig" settings.

MyConfig = SteemJConfig.getInstance ();

MyConfig.setEncodingCharset (Charset.forName ("UTF-8"));

MyConfig.setTimeout (100000L);
Try {
MyConfig.setWebsocketEndpointURI (new URI ("wss: //this.piston.rocks"));
MyConfig.setSslVerificationDisabled (true);
} Catch (URISyntaxException e) {
Throw new RuntimeException ("The given URI is not valid.", E);
}

MyConfig.setUsername ("sesangsokuro");
MyConfig.setPrivateKey (PrivateKeyType.POSTING, "someThing");
MyConfig.setPrivateKey (PrivateKeyType.ACTIVE, "someThing");

There are two secret keys.

**Comment by marvin-we** [comment]
Hallo @sesangsokuro , hallo @FullKickProductions,

thank both of your for your feedback. Both methods were not covered by tests so I've missed some changes due to HF 19. The last commit fixes the:
* getFeedHistory
* getOrderBook
* getOpenOrders 
Methods. 

Thank you again for improving this project <3 

@FullKickProductions : If you do not want to build the project from scratch please let me know. In that case I'll release version 0.3.1 this Sunday even if some planned features are not ready.

**Comment by FullKickProductions** [comment]
Thanks @marvin-we, I'll have a go at building it a bit later.
