### ISSUE TITLE
Run all integration tests against the TestNet provided by @almost-digital

### ISSUE THREAD

**Issue by sesangsokuro** [marvin-we/steem-java-api-wrapper#43]
[INFO] Running eu.bittrade.libs.steemj.configuration.SteemJConfigTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in eu.bittrade.libs.steemj.configuration.SteemJConfigTest
[ERROR] testSettingsThrougSystemProperties(eu.bittrade.libs.steemj.configuration.SteemJConfigTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: "dez1337"
     but: was ""
	at eu.bittrade.libs.steemj.configuration.SteemJConfigTest.testSettingsThrougSystemProperties(SteemJConfigTest.java:36)

**Comment by FullKickProductions** [comment]
Hi. The readme of this project says 

> Please notice that some integration tests require different private keys. Please provide them as -D parameter or use the properties file ( src/test/resources/accountDetailsUsedDuringTests.properties ) to define them. If you do not want to execute tests at all add "-Dmaven.test.skip" to the mvn call which skips the test execution during the build.

I think that would be one of those tests, I get the same test failure when building.

**Comment by marvin-we** [comment]
Hallo together,

sorry for the late reply, but I had to go on a business travel once again and just come back yesterday :/ 

Thank you @FullKickProductions for the reply, but actually it is only possible to run the tests with my own account :( The reason for this is that I my username is hardcoded in the tests and the exepected return values also depend on the used username so they will no longer match if another username is used. I guess that makes it more or less imposble atm to run integration tests for you. 

I have a solution in mind, but it will take some time to implement it so please stay tuned.

Thank you once again!

**Comment by marvin-we** [comment]
Found the problem with the specific unit test reported by @sesangsokuro - But I reopen this issue to keep the integration test issue in mind.

**Comment by marvin-we** [comment]
Running all tests against the test network offered by https://testnet.steem.vc could be a solution.
