### ISSUE TITLE
how to cancel active voting or down voting?

### ISSUE THREAD

**Issue by zizone** [marvin-we/steem-java-api-wrapper#48]
and How many amount of vote power did I vote before?

how to calculed that?

i can't found any way.

**Comment by marvin-we** [comment]
Hay @zizone,

thank you for creating this issue and asking the question. I've did a small test and as you can see on [steemd.com](https://steemd.com/tx/e206d1c19386f98eea36aafd3f9327a8fef0abf0) an "un-vote" is another VoteOperation on the same post while using a weight of 0.

The weight can be a value between 100 (100%) and -100 (-100%). 

To check the weight of earlier votes you have several options:
- If you know the block number you can use the getOpsInBlock method or the getBlock method.
- If you know the account name you can use the getAccountHistory method.

To check the remaining vote power for an account you should use the getAccount. The returned object has a getVotingPower method which returns the percentage of remaining voting power.

Please close this issue if all your questions are answered or feel free to ask some more ;) 

Thank you once again and best regards!

**Comment by marvin-we** [comment]
This will be simplified when #71 has been implemented.
