### ISSUE TITLE
SteemJ not working on Google App Engine

### ISSUE THREAD

**Issue by bonustrack** [marvin-we/steem-java-api-wrapper#53]
Issue moved from https://github.com/steemit/steem-js/issues/225 by @jan10101 

**Expected behavior**

Would be nice if I could use SteemJ in my maven project (Java) running on Google App Engine

**Actual behavior**

A class used by SteemJ seems to be restricted by App Engine and SteemJ can not be executed. The class is: java.lang.management.ManagementFactory

The error message thrown by App Engine:

Could not reconfigure JMX java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory is a restricted class. Please see the Google App Engine developer's guide for more details.

**How to reproduce**

Try to call SteemJConfig.getInstance(); in an App Engine project

**Comment by jan10101** [comment]
Thanks for moving and sorry for posting it at the wrong project

**Comment by marvin-we** [comment]
Hello @jan10101 ,

thank you for creating the issue. 

So I've checked the code of SteemJ and sadly, I am not using the ManagementFactory class myself. That means it is used by one of the dependencies of SteemJ (Maybe BitcoinJ). Do you have the full stacktrace available and can post it here? It would make the investigations a lot easier :) 

Thank you and best regards!

**Comment by jan10101** [comment]
Hi @marvin-we ,

I found a solution: By switching to Java 8 on Google AppEngine, they lifted these restriction and the class can be used.

Hope this will help someone else :)

Thanks and best regards
Jan

**Comment by marvin-we** [comment]
Thank you for the feedback - Good to know you've found a workaround. 👌

I close the issue for now.
