### ISSUE TITLE
'Test network mode' is not supported

### ISSUE THREAD

**Issue by ismelykh** [marvin-we/steem-java-api-wrapper#60]
Hi @marvin-we,

I found that my problem I was facing in #59 was caused by the lack of [test network mode](https://steem.io/documentation/how-to-start-a-testnet/) support.
You have to use specific chain id and adress prefix for the testing network mode, chain id could be passed as an argument for the Transaction.sign() method and prefix has to be 'TST' but it's hardcoded: https://github.com/marvin-we/steem-java-api-wrapper/blob/af2f76ca9d35728ab21ad605d772bce1a719d738/src/main/java/eu/bittrade/libs/steemj/base/models/PublicKey.java#L36

Regards.

**Comment by marvin-we** [comment]
Hay @ismelykh ,

Ah yes, I see :) Thank you for the update.

I think I'll just make both parameters and the chain id configurable in the SteemJConfig 👌

I'll keep you updated :)

**Comment by ismelykh** [comment]
I forgot to mention one more problem I found which is related.

https://github.com/marvin-we/steem-java-api-wrapper/blob/14a69c34dd6a6a8e1a10d2b138af2d9f2fa24b1b/src/main/java/eu/bittrade/libs/steemj/enums/AssetSymbolType.java#L11

In a test network you have TESTS, so it causes an exception during deserialization.
