### ISSUE TITLE
Unable to use insecure websockets connection

### ISSUE THREAD

**Issue by ismelykh** [marvin-we/steem-java-api-wrapper#61]
It seems that there is no way to use insecure websockets endpoint, calling SteemJConfig.setWebsocketEndpointURI() with url which looks like ws://x.x.x.x:port is always leads to 'Could not connect to the server' exception.

**Comment by marvin-we** [comment]
Hello @ismelykh ,

I could not find an unsecure puplic RPC node so I tried to use an websocket echo service. 

```JAVA
myConfig.setWebsocketEndpointURI(new URI("ws://echo.websocket.org:80"));
```

And it is working fine for me. Can you please verify that your Steem node is really listening on that URL/Port and that you do not face a firewall issues?

Thank you and best regards! :)

**Comment by ismelykh** [comment]
Hi @marvin-we 
I found what happens. 
The reason of this bug is https://github.com/marvin-we/steem-java-api-wrapper/blob/f10795fa6fceac9d96ae725679173ac02b6dca19/src/main/java/eu/bittrade/libs/steemj/communication/CommunicationHandler.java#L73

Websockets library enables ssl if there is SSL_ENGINE_CONFIGURATOR property.

For reproduce this issue just disable ssl verification and try any ws:// url.

**Comment by marvin-we** [comment]
Well done, you are a genius :D - I have some time at the weekend and will try to solve this asap :)
