### ISSUE TITLE
java.lang.ClassNotFoundException: eu.bittrade.libs.steemj.SteemJ

### ISSUE THREAD

**Issue by hswick** [marvin-we/steem-java-api-wrapper#79]
Can't seem to import this class even though I'm very aware it is in your source code.

Your documentation also seems to be wrong here:
Steemj steemJ = new Steemj();

Notice lowercase j while your class is upper case J, also you don't have an explicit import for the SteemJ class in your example on README.

**Comment by marvin-we** [comment]
Hay @hswick ,

thank you for creating an issue here :) Could you please tell me which version of SteemJ you are using? The renaming of the SteemApiWrapper to SteemJ has been done in version 0.4.0 which is currently not yet released (And that is also the reason why the sample is still using the SteemApiWrapper object).

You need to use SteemJ in version 0.3.4 with the sample provided or build version 0.4.0 on your local machine.

Please let me know if that helps :)

**Comment by hswick** [comment]
W using "0.3.2" and tried building with "0.3.4" and still received the error. 

I will wait for "0.4.0" release as my project is not urgent.

**Comment by marvin-we** [comment]
Hay @hswick ,

Sorry for the late reply, I totalky forgot this issue :/ The new version has been released, could you please test if the issue is now solved for you? 😊

Thanks and best regards
